import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Phylogeny of Life Science Tools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className="min-h-screen w-full bg-zinc-800 px-4 py-2 text-zinc-100">
        {children}
      </body>
    </html>
  );
}
