import Script from "next/script";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Phylogeny of Life Science Tools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <head>
        <Script
          data-goatcounter={"https://phylogeny.goatcounter.com/count"}
          data-goatcounter-settings='{"allow_local": false}'
          src="//gc.zgo.at/count.js"
        />
      </head>
      <body className="min-h-screen w-full bg-zinc-800 px-4 py-2 text-zinc-100">
        {children}
      </body>
    </html>
  );
}
